name: Test

on:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          path: 'action'
      - name: Checkout test repo
        uses: actions/checkout@v2.4.0
        with:
          repository: DanySK/Template-for-Gradle-Plugins
          path: 'target'
          ref: '21c1656dddad183d2639e8fa596fa4b48e890d28'
      - uses: ./action
        with:
          working-directory: target
          should-run-codecov: false
