name: CI/CD Process

on:
  push:
    branches-ignore:
      - 'renovate/**'
  pull_request:
  workflow_dispatch:

jobs:
  select-tests:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-select-tests-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    outputs:
      tests: ${{ steps.trick.outputs.tests }}
    steps:
      - name: Trick Renovate
        id: trick
        shell: bash
        run: |
          USES=$(cat <<TRICK_RENOVATE
          - uses: DanySK/Template-for-Gradle-Plugins@2.0.35
          - uses: DanySK/Template-for-Kotlin-Multiplatform-Projects@0.3.2
          TRICK_RENOVATE
          )
          export USES="$USES"
          ruby -e 'puts "tests=#{ENV["USES"].lines.map { |line| /^-\s+uses:\s+([^\s]+\/[^\s]+)@(.*)\s*$/.match(line) }.map { |match| [match[1], match[2]] }}"' >> $GITHUB_OUTPUT
  test:
    needs:
      - select-tests
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2025, macos-14, ubuntu-24.04 ]
        test: ${{ fromJson(needs.select-tests.outputs.tests) }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: ${{ github.workflow }}-test-${{ matrix.os }}-${{ matrix.test[0] }}-${{ matrix.test[1] }}-${{ github.event.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          path: 'action'
      - name: Checkout test repo
        uses: actions/checkout@v5.0.0
        with:
          repository: ${{ matrix.test[0] }}
          path: 'target'
          ref: ${{ matrix.test[1] }}
      - uses: ./action
        with:
          build-command: ./gradlew tasks
          check-command: |
            for x in 1 2 3; do
              echo $x
            done
          working-directory: target
          should-run-codecov: false
          clean-command: ./gradlew clean
      - uses: ./action
        with:
          working-directory: target
          should-run-codecov: false
  failure-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the Gradle wrapper
        uses: actions/checkout@v5.0.0
        with:
          repository: DanySK/gradle-wrapper
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          path: 'action'
      - uses: ./action
        id: just-false
        continue-on-error: true
        env:
          ATTEMPT: "0"
        with:
          build-command: |
            ATTEMPT=$( [ -f just-false ] && cat just-false || echo "0" )
            ATTEMPT=$((ATTEMPT + 1))
            echo "Attempt: $ATTEMPT"
            echo "$ATTEMPT" > just-false
            false
          check-command: true
          should-validate-wrapper: false
          enable-cache: false
          should-run-codecov: false
      - uses: ./action
        continue-on-error: true
        id: false-true
        with:
          build-command: |
            ATTEMPT=$( [ -f false-true ] && cat false-true || echo "0" )
            ATTEMPT=$((ATTEMPT + 1))
            echo "Attempt: $ATTEMPT"
            echo "$ATTEMPT" > false-true
            false
            true
          check-command: true
          should-validate-wrapper: false
          enable-cache: false
          should-run-codecov: false
      - name: Result
        if: always()
        run: |
          [ '${{ steps.just-false.outcome}}' = 'failure' ]
          echo "just-false failed successfully"
          echo "It ran for $(cat just-false) attempts, they should be 2"
          [ "$(cat just-false)" = '2' ]
          echo "they are."
          [ '${{ steps.false-true.outcome}}' = 'failure' ]
          echo "false-true failed successfully"
          echo "It ran for $(cat false-true) attempts, they should be 2"
          [ "$(cat false-true)" = '2' ]
          echo "they are."
  release:
    if: github.event_name == 'push'
    needs:
      - test
      - failure-tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
      - name: Install Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version-file: package.json
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx semantic-release
  success:
    runs-on: ubuntu-24.04
    needs:
      - select-tests
      - test
      - release
    if: >-
      always() && (
        contains(join(needs.*.result, ','), 'failure')
        || !contains(join(needs.*.result, ','), 'cancelled')
      )
    steps:
      - name: Verify that there were no failures
        run: ${{ !contains(join(needs.*.result, ','), 'failure') }}
